default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 10240
    epsilon: 0.2
    hidden_units: 64
    lambd: 0.95
    learning_rate: 3.0e-4
    learning_rate_schedule: linear
    max_steps: 5.0e5
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 2
    time_horizon: 64
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99

test:
    trainer: ppo
    batch_size: 512
    beta: 1.0e-2
    buffer_size: 8192
    epsilon: 0.2
    hidden_units: 32
    lambd: 0.95
    learning_rate: 1.0e-5
    learning_rate_schedule: linear
    max_steps: 1.0e5
    memory_size: 256
    normalize: true
    num_epoch: 3
    num_layers: 1
    time_horizon: 64
    sequence_length: 4
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.99
