default:
    trainer: ppo
    batch_size: 1024
    beta: 5.0e-3
    buffer_size: 40960
    epsilon: 0.15
    hidden_units: 64
    lambd: 0.95
    learning_rate: 1.0e-3
    learning_rate_schedule: linear
    max_steps: 1.0e6
    memory_size: 256
    normalize: false
    num_epoch: 5
    num_layers: 2
    time_horizon: 1024
    sequence_length: 64
    summary_freq: 1000
    use_recurrent: false
    vis_encode_type: simple
    reward_signals:
        extrinsic:
            strength: 1.0
            gamma: 0.995

